In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Just messing around with the data

In [3]:
data = pd.read_csv("athlete_events.csv")

In [4]:
data.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [5]:
data[data["Name"] == "Christine Jacoba Aaftink"]

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
5,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
6,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,Speed Skating Women's 500 metres,NaN
7,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
8,5,Christine Jacoba Aaftink,F,27.0,185.0,82.0,Netherlands,NED,1994 Winter,1994,Winter,Lillehammer,Speed Skating,Speed Skating Women's 500 metres,NaN
9,5,Christine Jacoba Aaftink,F,27.0,185.0,82.0,Netherlands,NED,1994 Winter,1994,Winter,Lillehammer,Speed Skating,"Speed Skating Women's 1,000 metres",NaN

In [6]:
data.groupby("Age").count()

,ID,Name,Sex,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
Age,,,,,,,,,,,,,,
10.0,1,1,1,0,0,1,1,1,1,1,1,1,1,1
11.0,13,13,13,8,6,13,13,13,13,13,13,13,13,1
12.0,39,39,39,29,29,39,39,39,39,39,39,39,39,6
13.0,187,187,187,164,161,187,187,187,187,187,187,187,187,16
14.0,837,837,837,727,722,837,837,837,837,837,837,837,837,75
15.0,2203,2203,2203,1900,1881,2203,2203,2203,2203,2203,2203,2203,2203,196
16.0,3852,3852,3852,3265,3207,3852,3852,3852,3852,3852,3852,3852,3852,350
17.0,5376,5376,5376,4376,4306,5376,5376,5376,5376,5376,5376,5376,5376,534
18.0,8152,8152,8152,6688,6583,8152,8152,8152,8152,8152,8152,8152,8152,860
19.0,11643,11643,11643,9297,9191,11643,11643,11643,11643,11643,11643,11643,11643,1369
20.0,15258,15258,15258,12346,12200,15258,15258,15258,15258,15258,15258,15258,15258,2004
21.0,19164,19164,19164,15649,15444,19164,19164,19164,19164,19164,19164,19164,19164,2684
22.0,20814,20814,20814,17112,16924,20814,20814,20814,20814,20814,20814,20814,20814,3159
23.0,21875,21875,21875,18068,17840,21875,21875,21875,21875,21875,21875,21875,21875,3395
24.0,21720,21720,21720,17813,17648,21720,21720,21720,21720,21720,21720,21720,21720,3289
25.0,19707,19707,19707,16553,16383,19707,19707,19707,19707,19707,19707,19707,19707,3124
26.0,17675,17675,17675,14737,14588,17675,17675,17675,17675,17675,17675,17675,17675,2924
27.0,16025,16025,16025,13445,13316,16025,16025,16025,16025,16025,16025,16025,16025,2690
28.0,14043,14043,14043,11775,11695,14043,14043,14043,14043,14043,14043,14043,14043,2335
29.0,11463,11463,11463,9436,9345,11463,11463,11463,11463,11463,11463,11463,11463,1941
30.0,9488,9488,9488,7656,7602,9488,9488,9488,9488,9488,9488,9488,9488,1599
31.0,7559,7559,7559,6097,6010,7559,7559,7559,7559,7559,7559,7559,7559,1250
32.0,6246,6246,6246,5015,4924,6246,6246,6246,6246,6246,6246,6246,6246,1011
33.0,4800,4800,4800,3744,3697,4800,4800,4800,4800,4800,4800,4800,4800,792
34.0,3985,3985,3985,2901,2877,3985,3985,3985,3985,3985,3985,3985,3985,640
35.0,3133,3133,3133,2202,2141,3133,3133,3133,3133,3133,3133,3133,3133,485
36.0,2503,2503,2503,1784,1726,2503,2503,2503,2503,2503,2503,2503,2503,383
37.0,1953,1953,1953,1306,1265,1953,1953,1953,1953,1953,1953,1953,1953,277
38.0,1612,1612,1612,1004,983,1612,1612,1612,1612,1612,1612,1612,1612,245
39.0,1405,1405,1405,864,805,1405,1405,1405,1405,1405,1405,1405,1405,188
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54.0,162,162,162,55,52,162,162,162,162,162,162,162,162,26
55.0,104,104,104,24,23,104,104,104,104,104,104,104,104,14
56.0,131,131,131,40,38,131,131,131,131,131,131,131,131,20
57.0,69,69,69,21,20,69,69,69,69,69,69,69,69,7
58.0,84,84,84,17,17,84,84,84,84,84,84,84,84,12
59.0,87,87,87,13,10,87,87,87,87,87,87,87,87,6
60.0,88,88,88,19,18,88,88,88,88,88,88,88,88,12
61.0,68,68,68,15,14,68,68,68,68,68,68,68,68,6
62.0,62,62,62,6,6,62,62,62,62,62,62,62,62,0
63.0,56,56,56,8,6,56,56,56,56,56,56,56,56,9
64.0,30,30,30,2,2,30,30,30,30,30,30,30,30,3
65.0,84,84,84,12,7,84,84,84,84,84,84,84,84,1
66.0,31,31,31,6,6,31,31,31,31,31,31,31,31,2
67.0,25,25,25,2,2,25,25,25,25,25,25,25,25,0
68.0,25,25,25,1,1,25,25,25,25,25,25,25,25,2
69.0,60,60,60,2,2,60,60,60,60,60,60,60,60,2
70.0,28,28,28,2,2,28,28,28,28,28,28,28,28,0
71.0,33,33,33,2,1,33,33,33,33,33,33,33,33,2
72.0,24,24,24,0,0,24,24,24,24,24,24,24,24,2
73.0,8,8,8,0,0,8,8,8,8,8,8,8,8,1
74.0,12,12,12,0,0,12,12,12,12,12,12,12,12,0
75.0,4,4,4,0,0,4,4,4,4,4,4,4,4,0
76.0,7,7,7,0,0,7,7,7,7,7,7,7,7,0
77.0,2,2,2,0,0,2,2,2,2,2,2,2,2,0
80.0,3,3,3,0,0,3,3,3,3,3,3,3,3,0
81.0,2,2,2,0,0,2,2,2,2,2,2,2,2,0
84.0,1,1,1,0,0,1,1,1,1,1,1,1,1,0
88.0,3,3,3,0,0,3,3,3,3,3,3,3,3,0
96.0,1,1,1,0,0,1,1,1,1,1,1,1,1,0
97.0,1,1,1,0,0,1,1,1,1,1,1,1,1,0

In [7]:
this_year = data[data["Year"] == 2016]

In [8]:
len(this_year)

13688

In [9]:
fieldnames = list(data.columns)
fieldnames

['ID',
 'Name',
 'Sex',
 'Age',
 'Height',
 'Weight',
 'Team',
 'NOC',
 'Games',
 'Year',
 'Season',
 'City',
 'Sport',
 'Event',
 'Medal']

In [14]:
import csv
import json

with open('athlete_events.csv') as f:
    reader = csv.DictReader(f)
    rows = list(reader)

with open('olympians.json', 'w') as f:
    json.dump(rows, f)

In [15]:
usa = data[data["NOC"] == "USA"]

In [17]:
usa.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
10,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
11,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,NaN
12,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,NaN
13,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
14,6,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN

In [18]:
usa.groupby("Year").count()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Season,City,Sport,Event,Medal
Year,,,,,,,,,,,,,,
1896,27,27,27,27,16,13,27,27,27,27,27,27,27,20
1900,135,135,135,130,42,34,135,135,135,135,135,135,135,63
1904,1109,1109,1109,887,172,115,1109,1109,1109,1109,1109,1109,1109,394
1906,81,81,81,81,59,59,81,81,81,81,81,81,81,24
1908,219,219,219,214,147,141,219,219,219,219,219,219,219,65
1912,364,364,364,362,218,180,364,364,364,364,364,364,364,107
1920,473,473,473,471,305,143,473,473,473,473,473,473,473,194
1924,500,500,500,498,298,120,500,500,500,500,500,500,500,194
1928,471,471,471,451,162,128,471,471,471,471,471,471,471,102
1932,813,813,813,783,154,133,813,813,813,813,813,813,813,223
1936,561,561,561,556,138,137,561,561,561,561,561,561,561,112
1948,521,521,521,521,188,186,521,521,521,521,521,521,521,168
1952,547,547,547,547,220,216,547,547,547,547,547,547,547,164
1956,535,535,535,535,461,463,535,535,535,535,535,535,535,149
1960,533,533,533,533,475,474,533,533,533,533,533,533,533,152
1964,619,619,619,619,619,619,619,619,619,619,619,619,619,177
1968,664,664,664,664,664,664,664,664,664,664,664,664,664,173
1972,725,725,725,725,719,720,725,725,725,725,725,725,725,195
1976,705,705,705,705,660,660,705,705,705,705,705,705,705,175
1980,155,155,155,155,144,144,155,155,155,155,155,155,155,30
1984,849,849,849,847,842,842,849,849,849,849,849,849,849,361
1988,912,912,912,910,896,897,912,912,912,912,912,912,912,214
1992,968,968,968,967,955,956,968,968,968,968,968,968,968,238
1994,237,237,237,237,232,232,237,237,237,237,237,237,237,19
1996,839,839,839,839,759,746,839,839,839,839,839,839,839,259
1998,284,284,284,284,283,283,284,284,284,284,284,284,284,34
2000,764,764,764,764,760,759,764,764,764,764,764,764,764,242
2002,313,313,313,313,313,311,313,313,313,313,313,313,313,84
2004,726,726,726,726,724,723,726,726,726,726,726,726,726,263
2006,325,325,325,325,325,324,325,325,325,325,325,325,325,52
2008,763,763,763,763,763,756,763,763,763,763,763,763,763,317
2010,341,341,341,341,341,341,341,341,341,341,341,341,341,97
2012,689,689,689,689,689,689,689,689,689,689,689,689,689,248
2014,367,367,367,367,367,367,367,367,367,367,367,367,367,64
2016,719,719,719,719,718,718,719,719,719,719,719,719,719,264

In [19]:
summer = data[data["Season"] == "Summer"]

In [20]:
usa_summer = summer[summer["NOC"] == "USA"]

In [ ]:
usa_summer.groupby("Year").count()